spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${dixit.mongodb.uri}
jwt:
  secret: ${dixit.jwt.secret}

dixit:
  service:
    name: Dixit
    host: ${DIXIT_SERVICE_HOST:PLACEHOLDER}
  mongodb:
    uri: ${MONGO_URI:PLACEHOLDER}
  jwt:
    secret: ${JWT_SECRET_KEY:PLACEHOLDER}

lobby:
  service:
    host: ${LOBBY_SERVICE_HOST:PLACEHOLDER}